pinup/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse
from django.views.generic.base import RedirectView

def robots(request):
    return HttpResponse('User-agent: *\nDisallow: /', content_type='text/plain')

urlpatterns = [
    path('robots.txt', robots),
    path('admin/', admin.site.urls),
    path('wiki/', include('wiki.urls')),
    path('distribution/', include('distribution.urls')),
    path('clockout/', include('clockout.urls')),
    path('calendar/', include('poster_calendar.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', RedirectView.as_view(pattern_name='wiki:index', permanent=True), name='index')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wiki/urls.py
from django.urls import path, register_converter

from . import views, converters
register_converter(converters.PathConverter, 'page')

app_name = 'wiki'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
	path('_create', views.create, name='create'),
	path('_upload', views.upload, name='upload'),
	path('<page:page_path>', views.detail, name='detail'),
	path('<page:page_path>/_create', views.create, name='create'),
	path('<page:page_path>/_upload', views.upload, name='upload'),
	path('<page:page_path>/_update', views.update, name='update'),
	path('<page:page_path>/_delete', views.delete, name='delete'),
	path('<page:page_path>/_revert/<int:edit_number>', views.revert, name='revert'),
	path('<page:page_path>/_history', views.history, name='history'),

	#path('<page:page_path>/_move', views.page_move, name='page_move'),
	#path('<page:page_path>/_clone', views.page_clone, name='page_clone'),
	#path('<page:page_path>/_source', views.page_source, name='page_source'),
]

wiki/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from diff_match_patch import diff_match_patch

from accounts.models import User

#pages store the most recent version of a file
class PageBase(models.Model):
    title = models.CharField(max_length=100, null=True)
    slug = models.SlugField(max_length=115, blank=True, null=True)

    created_date = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    class Meta:
        abstract = True

class Page(PageBase):
    parent = models.ForeignKey("self", null=True, blank=True, on_delete=models.CASCADE, related_name="child")
    content = models.TextField(blank=True)#MarkdownxField(default="", max_length="10000", blank=True)
    file = models.FileField(upload_to='uploads', blank=True)
    class protection_choices(models.TextChoices):
        NO = 'NO', _('None') #all signed in users can edit
        LO = 'LO', _('Locked') #only created_by user can edit
        NC = 'NC', _('Locked and doesn\'t allow children') #only created_by user can edit, and prevents children from being created

    protection = models.CharField(
        help_text="Setting the protection to 'locked' will not allow others to edit this page in the future.",
        max_length=2,
        choices=protection_choices.choices,
        default=protection_choices.NO,
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(fields= ['parent','title'], name='unique_page_title'),
            models.UniqueConstraint(fields= ['parent','slug'], name='unique_page_slug'),
        ]
        ordering = ['title']

    def get_absolute_url(self):
        if self.parent:
            return self.parent.get_absolute_url() + '/' + self.slug
        else:
            return '/' + self.slug

    def get_url(self):
        #this isn't an absolute url path, because it misses the first '/',
        #but it's used in the urls
        return self.get_absolute_url()[1:]

    def __str__(self):
        return self.title
    def save(self, *args, **kwargs):
        if not self.id: # we're creating this for the first time
            if not self.slug:
                self.slug = slugify(self.title)
        super(Page, self).save(*args, **kwargs)

    @property
    def get_latest_revision(self):
        try:
            return Revision.objects.filter(page__id=self.id, latest=True).get()
        except:
            return None

    @property
    def edit_date(self):
        revision = self.get_latest_revision
        if revision:
            return revision.created_date
        return self.created_date

    def revert(self, count=0):
        dmp = diff_match_patch()
        modified_fields = set()
        for i in range(count+1): #so we can start at 0, I like that
            revision = self.get_latest_revision
            fields = ['slug', 'parent', 'title', 'created_date', 'created_by']
            #fields = ['slug', 'title', 'created_date', 'created_by']
            for field in fields: #set the relevant fields
                value = getattr(revision, field)
                if value is not None:
                    if value != getattr(self, field):
                        modified_fields.add(Page._meta.get_field(field).verbose_name)
                    self.__setattr__(field, value)
            if self.content and revision.patch:
                modified_fields.add(Page._meta.get_field('content').verbose_name)
                patches = dmp.patch_fromText(revision.patch)
                new_content, _ = dmp.patch_apply(patches, self.content)
                self.content = new_content
            if revision.parent != None and revision.parent != self.parent:
                self.parent = revision.parent
            prev_revision = revision.get_previous
            if prev_revision:
                prev_revision.latest = True; prev_revision.save()
            revision.delete()
            #make the previous revision the new latest one, if there is one
            self.save()
        if Page._meta.get_field('content').verbose_name not in modified_fields:
            modified_fields.add(Page._meta.get_field('title').verbose_name)
            #^since revisions are only created when we change content or title, then there
            #must've been a title change
        success_msg = f"reverted fields: {', '.join(sorted(list(modified_fields)))}"
        return success_msg

    def delete(self, *args, **kwargs):
        if self.file:
            self.file.delete()
        super().delete(*args, **kwargs)


#used to go from the current version to the previous version
class Revision(PageBase):
    page = models.ForeignKey(Page, on_delete=models.CASCADE, related_name="revision")
    parent = models.ForeignKey(Page, null=True, blank=True, on_delete=models.SET_NULL, related_name="revisions_parent") #where the file WAS saved at this time
    #if this is null, then it either has no parent or it has the same parent
    edit_number = models.PositiveSmallIntegerField(default=0)
    edit_summary = models.CharField(max_length=255, blank=True, null=True)
    latest = models.BooleanField(default=False)

    patch = models.TextField(null=True)

    class Meta:
        ordering = ['-latest', '-created_date']
        constraints = [
            models.UniqueConstraint(fields= ['parent','edit_number'], name='unique_edit_number'),
        ]

    @property
    def get_previous(self):
        if self.edit_number and self.edit_number > 0:
            return Revision.objects.filter(edit_number = self.edit_number - 1)[0]
        else:
            return None

    #returns how many times we have to call revert on page to get to this revision
    #returns negative if revision doesn't belong to page (shouldn't happen if done correctly)
    def get_revert_count(self, page):
        if self.page != page:
            return -1
        return page.get_latest_revision.edit_number - self.edit_number

    def __str__(self):
        s = f"Edit #{self.edit_number +1}" + ", " + self.created_date.strftime("%b. %d, %Y, %H:%m")
        if self.created_by:
            s += ", by " + str(self.created_by)
        else:
            s += ", deleted user"
        return s

    def save(self, *args, **kwargs):
        if not self.id: # we're creating this for the first time
            if self.title and not self.slug:
                self.slug = slugify(self.title)
        super(Revision, self).save(*args, **kwargs)

wiki/forms.py
import datetime

from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.utils.text import slugify

from .models import *

class PageBaseForm(ModelForm):
    class Meta:
        model = Page
        fields = ['title', 'protection', 'content', 'file']
        #help_texts = {'edit_summary': _('Briefly describe your changes'),}

    def clean_slug(self):
        slug = self.cleaned_data['slug']
        slug = slugify(slug)
        if slug in ['_create', '_update', '_clone', '_move', '_history']:
            raise ValidationError(_('Slug cannot have this value. (Try using a different word, or not using an underscore at the beginning.)'))
        if len(slug)>= 1 and not slug[0].isalpha():
            raise ValidationError('The first character of a slug must be a letter character.)')
        return slug

    def clean_protection(self):
        protection = self.cleaned_data['protection']
        if protection not in ['NO', 'LO', 'NC']:
            raise ValidationError('Protection must be one of three values determined by this site. Refresh the page and try again.)')
        return protection

class PageForm(PageBaseForm):
    def __init__(self, *args, **kwargs):
        super(PageForm, self).__init__(*args, **kwargs)
        self.fields.pop('file')

class PageFileForm(PageBaseForm):
    def __init__(self, *args, **kwargs):
        super(PageFileForm, self).__init__(*args, **kwargs)
        self.fields.pop('content')

wiki/templates/wiki/delete.html
{% extends "base.html" %}

{% block title %}Delete {{ page.title }}{% endblock %}

{% block content %}
<a href="{% url 'wiki:detail' page.get_url %}">back to {{ page.title }}</a>
<h1>delete {{ page.title }}?</h1>

<p>Are you sure you want to delete this page?</p>
{% if page.child.all %}
<p><b>Doing so will also delete all the children under this page:</b></p>
<ul>
	{% for child in page.child.all %}
		<li>{{ child }}</li>
	{% endfor %}
</ul>
{% endif %}

<form method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Delete">
</form>

{% endblock %}

wiki/templates/wiki/detail.html
{% extends "base.html" %}
{% load wiki_filters %}

{% block title %}{{ page.title }}{% endblock %}

{% block content %}
<p><a href="{% url 'wiki:index' %}">back to all pages</a></p>
<p>
  {% if page.parent %}parent: <a href="{% url 'wiki:detail' page.parent.get_url %}">{{ page.parent }}</a> |{% endif %}
  {% if user == page.created_by or page.protection == "NO" %}<a href="{% url 'wiki:update' page.get_url %}">update page</a> |
  <a href="{% url 'wiki:delete' page.get_url %}">delete page</a> |{% endif %}
  <a href="{% url 'wiki:history' page.get_url %}">version history</a>
</p>
<p>Protection: {{ page.get_protection_display }}</p>
<h1>{{ page.title }}</h1>

{% if page.content %}<p class='pre'>{{ page.content }}</p>{% endif %}
{{ page.file|preview }}

<p><a href="{% url 'wiki:create' page.get_url %}">Create child page here</a></p>
<p><a href="{% url 'wiki:upload' page.get_url %}">Upload a file here</a></p>

{% if page.child.all %}
<hr>
<h1>Children</h1>
<ul>
{% for child in page.child.all %}
<li><a href="{% url 'wiki:detail' child.get_url %}">{{ child }}</a></li>
{% endfor %}
</ul>
{% endif %}
{% endblock %}

wiki/templates/wiki/form.html
{% extends "base.html" %}

{% block title %}{% if create %}Create new page{% if page %} under {{ page.title }}{% endif %}{% else %}Update page {{ page.title }}{% endif %}{% endblock %}

{% block content %}
{% if page %}<a href="{% url 'wiki:detail' page.get_url %}">back to {{ page.title }}</a>{% endif %}
<h1>{% if create %}Create new page{% if page %} under {{ page.title }}{% endif %}{% else %}Update page {{ page.title }}{% endif %}</h1>

<form method="post" {% if form.file %}enctype="multipart/form-data"{% endif %}>
  {% csrf_token %}
  <div class='form grid'>
  {{ form }}
  </div>
  <input type="submit" value="Submit">
</form>

{% endblock %}

wiki/templates/wiki/history.html
{% extends "base.html" %}

{% block title %}version history: {{ page.title }}{% endblock %}

{% block content %}
<p><a href="{% url 'wiki:detail' page.get_url  %}">back to page</a></p>
<h1>version history: {{ page.title }}</h1>

<details>
	<summary>current | {{ page.created_by }}</summary>
	<p class='pre'>{{ page.content }}</p>
</details>

{% if versions %}
{% for version in versions %}
<details class='version'>
	<summary>{{ version.0.created_date }}| {{ version.0.created_by }}</summary>
	<p class='pre'>{{ version.1 }}</p>

  {% if user == page.created_by or page.protection == "NO" %}<a class='revertLink' href="#" onclick="revert('{% url "wiki:revert" page.get_url version.0.edit_number %}', {{ version.0.edit_number }})">revert to this version</a>{% endif %}
</details>
{% endfor %}
{% else %}
<p>there are no other versions of this page</p>
{% endif %}

<script>
  function revert(redirect, edit_number){
    if (confirm("Are you sure you wish to revert to version " + edit_number + "?\
			\nThis cannot be undone.")){
			window.location.href = redirect;
		}
	}
</script>
{% endblock %}

wiki/templates/wiki/index.html
{% extends "base.html" %}
{% load wiki_filters %}

{% block title %}Pin Up Posters Courrier Collective Wiki{% endblock %}

{% block content %}
<h1>Pin Up Posters Courrier Collective Wiki</h1>
<p>A place to create notes, upload files, and to generally store as a knowledge base for Pin Up.</p>
<p><a href="{% url 'wiki:create' %}">create a page</a></p>
<p><a href="{% url 'wiki:upload' %}">upload a file</a></p>
<h2>All Wiki Pages (alphabetical order)</h2>
<ul>
  {{ pages|my_unordered_list }}
</ul>
{% endblock %}

wiki/templates/wiki/update_form_snippet.html
{{ errors }}
{% if errors and not fields %}
  {% for field in hidden_fields %}{{ field }}{% endfor %}
{% endif %}
{% for field, errors in fields %}
  {{ errors }}
    {% if field.label %}{{ field.label_tag }}{% endif %}
    {% if field.name == "file" %}<div>{% endif %}
    {{ field }}
    {% if field.help_text %}
      <br>
      <span class="helptext">{{ field.help_text }}</span>
    {% endif %}
    {% if forloop.last %}
      {% for field in hidden_fields %}{{ field }}{% endfor %}
    {% endif %}
    {% if field.name == file %}</div>{% endif %}
{% endfor %}
{% if not fields and not errors %}
  {% for field in hidden_fields %}{{ field }}{% endfor %}
{% endif %}