pinup/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse
from django.views.generic.base import RedirectView

def robots(request):
    return HttpResponse('User-agent: *\nDisallow: /', content_type='text/plain')

urlpatterns = [
    path('robots.txt', robots),
    path('admin/', admin.site.urls),
    path('wiki/', include('wiki.urls')),
    path('distribution/', include('distribution.urls')),
    path('clockout/', include('clockout.urls')),
    path('calendar/', include('poster_calendar.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', RedirectView.as_view(pattern_name='wiki:index', permanent=True), name='index')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

poster_calendar/urls.py
from django.urls import path

from . import views

app_name = 'calendar'
urlpatterns = [
    path('', views.PosterIndex.as_view(), name='index'),
    path('add', views.PosterCreate.as_view(), name='create'),
    path('<int:pk>/edit', views.PosterUpdate.as_view(), name='update'),
    path('<int:pk>/delete', views.PosterDelete.as_view(), name='delete'),
]

wiki/urls.py
from django.urls import path, register_converter

from . import views, converters
register_converter(converters.PathConverter, 'page')

app_name = 'wiki'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
	path('_create', views.create, name='create'),
	path('_upload', views.upload, name='upload'),
	path('<page:page_path>', views.detail, name='detail'),
	path('<page:page_path>/_create', views.create, name='create'),
	path('<page:page_path>/_upload', views.upload, name='upload'),
	path('<page:page_path>/_update', views.update, name='update'),
	path('<page:page_path>/_delete', views.delete, name='delete'),
	path('<page:page_path>/_revert/<int:edit_number>', views.revert, name='revert'),
	path('<page:page_path>/_history', views.history, name='history'),

	#path('<page:page_path>/_move', views.page_move, name='page_move'),
	#path('<page:page_path>/_clone', views.page_clone, name='page_clone'),
	#path('<page:page_path>/_source', views.page_source, name='page_source'),
]

poster_calendar/models.py
from django.db import models
from django.utils import timezone
from datetime import timedelta

from distribution.models import Neighborhood
from accounts.models import User

def get_take_down_date():
    return (timezone.now() + timedelta(days=3 * 365 / 12)).date()

BOOL_CHOICES = ((True, 'poster'), (False, 'handbill'))
class Poster(models.Model):
    name = models.CharField(null=True, unique=True, max_length=255)
    poster_type = models.BooleanField('type', choices=BOOL_CHOICES, default=True)
    notes = models.TextField(null=True, blank=True)
    neighborhoods = models.ManyToManyField(Neighborhood, related_name='posters')
    put_up_date = models.DateField(default=timezone.now)
    take_down_date = models.DateField(default=get_take_down_date, null=True, blank=True)

    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

    @property
    def is_past_takedown(self):
        return timezone.now().date() > self.take_down_date

    class Meta:
        ordering = ['-take_down_date', '-put_up_date']

poster_calendar/forms.py
import datetime

from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError

from .models import Poster

class DateInput(forms.DateInput):
    input_type = 'date'

class PosterForm(ModelForm):
    class Meta:
        model = Poster
        exclude = ['created_date']
        widgets = {
            'poster_type': forms.RadioSelect(),
            'put_up_date': DateInput(),
            'take_down_date': DateInput(),
            'neighborhoods': forms.CheckboxSelectMultiple(),
            'notes': forms.Textarea(attrs={'rows':0, 'cols':0}),
        }

    def clean_take_down_date(self):
        take_down_date = self.cleaned_data['take_down_date']
        put_up_date = self.cleaned_data['put_up_date']
        if take_down_date < put_up_date:
            raise ValidationError('Take down date must be after put up date')
        return take_down_date

poster_calendar/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from .models import Poster
from .forms import PosterForm

# Create your views here.

class PosterIndex(generic.ListView):
    template_name = 'poster_calendar/index.html'
    #context_object_name = 'posters'
    context_object_name = 'days'

    def get_queryset(self):
        #return Poster.objects.all()
        posters = Poster.objects.all()
        days_dict = {}
        for p in posters:
           days_dict[p.take_down_date] = days_dict.get(p.take_down_date, []) + [p]
        return days_dict

class PosterCreate(SuccessMessageMixin, generic.edit.CreateView):
    model = Poster
    template_name = 'poster_calendar/form.html'
    form_class = PosterForm
    success_message = "successfully added %(poster_type)s"

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            poster_type=self.object.get_poster_type_display(),
        )

    def get_success_url(self):
        return reverse('calendar:index')

class PosterUpdate(SuccessMessageMixin, generic.edit.UpdateView):
    model = Poster
    template_name = 'poster_calendar/form.html'
    form_class = PosterForm
    success_message = "successfully updated %(poster_type)s"

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            poster_type=self.object.get_poster_type_display(),
        )

    def get_success_url(self):
        return reverse('calendar:index')

class PosterDelete(SuccessMessageMixin, generic.edit.DeleteView):
    model = Poster
    template_name = 'poster_calendar/delete.html'
    success_message = 'successfully deleted poster'

    def get_success_url(self):
        return reverse('calendar:index')

poster_calendar/templates/poster_calendar/delete.html
{% extends "base.html" %}

{% block title %}Delete {{ poster.get_poster_type_display }} "{{ object }}"{% endblock %}

{% block content %}
<a href="{% url 'calendar:index' %}">back to calendar</a>
<h1>Delete poster "{{ object }}"?</h1>

<p>Are you sure you want to delete the {{ poster.get_poster_type_display }} "{{ object }}"?</p>

<form method="post">
	{% csrf_token %}
	{{ form }}
	<input type="submit" value="Delete">
</form>

{% endblock %}

poster_calendar/templates/poster_calendar/form.html
{% extends "base.html" %}

{% block title %}{% if poster %}Update {{ poster.get_poster_type_display }} | {{ poster }}{% else %}Add a Poster/Handbill{% endif %}{% endblock %}

{% block content %}
<a href="{% url 'calendar:index' %}">back to calendar</a>
<h1>{% if poster %}update {{ poster.get_poster_type_display }} | {{ poster }}{% else %}add a poster/handbill{% endif %}</h1>

<form method="post">
	{% csrf_token %}
  <div class='form grid'>
	{{ form }}
  </div>
	<input type="button" value="Set take down date to 3 months after put up date" onclick="change_take_down_date()">
	<input type="submit" value="Submit">
</form>

<script>
	var takedown_el = document.getElementById("id_take_down_date");
	var putup_el = document.getElementById("id_put_up_date");
	function change_take_down_date(){
		var my_date = putup_el.valueAsDate;
		my_date.setMonth(my_date.getMonth() + 3);
		takedown_el.value = my_date.toISOString().split('T')[0];
	}
</script>

{% endblock %}

poster_calendar/templates/poster_calendar/index.html
{% extends "base.html" %}

{% block title %}Poster Calendar{% endblock %}

{% block content %}
<h1>Poster Calendar</h1>
<p><a href='{% url "calendar:create" %}'>add a poster/handbill</a></p>
<p>Posters organized by take down date.</p>
{% for day, posters in days.items %}
<div class='calendar_entry'>
  <h2>{{ day }}</h2>
  <div class='entry_container'>
  {% for poster in posters %}
  <div class='entry'>
    <div class='tag is-{% if poster.poster_type %}info{% else %}warning{% endif %}'>{{ poster.get_poster_type_display }}</div>
    {% if poster.is_past_takedown %}<div class='tag is-error'>take down</div>{% endif %}
    <h3>{{ poster }}</h3>
    | <a href='{% url "calendar:update" poster.pk %}'>edit</a> | <a href='{% url "calendar:delete" poster.pk %}'>delete</a>
    <p class='info'>put up {{ poster.put_up_date }}</p>
    <p class='info'>neighborhoods: {% for n in poster.neighborhoods.all %}{{ n }}{% if forloop.counter != poster.neighborhoods.count %}, {% endif %}{% endfor %}</p>
    <p>{% if poster.notes %}{{ poster.notes }}{% else %}No notes{% endif %}</p>
  </div>
  {% endfor %}
  </div>
</div>
{% endfor %}
{% endblock %}