distribution/urls.py
from django.urls import path

from . import views

app_name = 'distribution'
urlpatterns = [
    path('', views.NeighborhoodIndex.as_view(), name='neighborhood_index'),
    path('data.json', views.distribution_json, name='distribution_json'),

    path('<slug:slug>', views.NeighborhoodDetail.as_view(), name='neighborhood_detail'),
    path('<slug:neighborhood>/update_assigned_members', views.update_assigned_members, name='update_assigned_members'),

    path('<slug:neighborhood>/add_area', views.area_create, name='area_create'),
    path('update_area/<int:area>', views.area_update, name='area_update'),
    path('delete_area/<int:pk>', views.AreaDelete.as_view(), name='area_delete'),

    path('<slug:neighborhood>/add_location', views.location_create, name='location_create'),
    path('add_location', views.location_create, name='location_create'),
    path('<slug:neighborhood>/<int:pk>', views.LocationDetail.as_view(), name='location_detail'),
    path('<slug:neighborhood>/<int:pk>/update', views.LocationUpdate.as_view(), name='location_update'),
    path('<slug:neighborhood>/<int:pk>/delete', views.LocationDelete.as_view(), name='location_delete'),

]

pinup/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse
from django.views.generic.base import RedirectView

def robots(request):
    return HttpResponse('User-agent: *\nDisallow: /', content_type='text/plain')

urlpatterns = [
    path('robots.txt', robots),
    path('admin/', admin.site.urls),
    path('wiki/', include('wiki.urls')),
    path('distribution/', include('distribution.urls')),
    path('clockout/', include('clockout.urls')),
    path('calendar/', include('poster_calendar.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', RedirectView.as_view(pattern_name='wiki:index', permanent=True), name='index')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wiki/urls.py
from django.urls import path, register_converter

from . import views, converters
register_converter(converters.PathConverter, 'page')

app_name = 'wiki'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
	path('_create', views.create, name='create'),
	path('_upload', views.upload, name='upload'),
	path('<page:page_path>', views.detail, name='detail'),
	path('<page:page_path>/_create', views.create, name='create'),
	path('<page:page_path>/_upload', views.upload, name='upload'),
	path('<page:page_path>/_update', views.update, name='update'),
	path('<page:page_path>/_delete', views.delete, name='delete'),
	path('<page:page_path>/_revert/<int:edit_number>', views.revert, name='revert'),
	path('<page:page_path>/_history', views.history, name='history'),

	#path('<page:page_path>/_move', views.page_move, name='page_move'),
	#path('<page:page_path>/_clone', views.page_clone, name='page_clone'),
	#path('<page:page_path>/_source', views.page_source, name='page_source'),
]

distribution/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify

from accounts.models import User

class Neighborhood(models.Model):
    name = models.CharField(null=True, unique=True, max_length=255)
    slug = models.SlugField(blank=True, null=True, unique=True)
    notes = models.TextField(null=True, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    users = models.ManyToManyField(User, related_name="neighborhoods", blank=True)

    @property
    def handbillspots(self):
        return len([i for i in self.location.all() if i.has_handbill_spot])
    @property
    def posterspots(self):
        return len([i for i in self.location.all() if i.has_poster_spot])


    def __str__(self):
        return self.name
    class Meta:
        ordering = ['name']

    def save(self, *args, **kwargs):
        if not self.id and not self.slug: # we're creating this for the first time
            self.slug = slugify(self.name)
        super(Neighborhood, self).save(*args, **kwargs)

class Area(models.Model):
    name = models.CharField(max_length=255)
    neighborhood = models.ForeignKey(Neighborhood, null=True, on_delete=models.CASCADE, related_name='area')
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['created_date']

BOOL_CHOICES = ((True, 'Yes'), (False, 'No'))

class Location(models.Model):
    name = models.CharField(null=True, max_length=255)
    address = models.CharField(null=True, blank=True, max_length=255)
    neighborhood = models.ForeignKey(Neighborhood, null=True, on_delete=models.SET_NULL, related_name='location')
    area = models.ForeignKey(Area, null=True, blank=True, on_delete=models.SET_NULL, related_name='location')
    has_poster_spot = models.BooleanField("Posters?", choices=BOOL_CHOICES)
    has_handbill_spot = models.BooleanField("Handbills?", choices=BOOL_CHOICES)
    notes = models.TextField(null=True, blank=True)
    hours = models.TextField(null=True, blank=True)

    lat = models.DecimalField(max_digits=9, decimal_places=5, null=True, blank=True)
    lon = models.DecimalField(max_digits=9, decimal_places=5, null=True, blank=True)

    created_date = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['created_date']

distribution/forms.py
import datetime

from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.utils.text import slugify

from .models import *

class LocationForm(ModelForm):
    class Meta:
        model = Location
        exclude = ['created_date', 'created_by']
        widgets = {
            'lat': forms.HiddenInput(),
            'lon': forms.HiddenInput(),
            'notes': forms.Textarea(attrs={'rows':0, 'cols':0}),
            'hours': forms.Textarea(attrs={'rows':0, 'cols':0}),
        }
        #help_texts = {'edit_summary': _('Briefly describe your changes'),}

    def clean_lat(self):
        lat = self.cleaned_data['lat']
        if lat and not -180 < lat < 180:
            raise ValidationError('Invalid latitude value')
        return lat

    def clean_lon(self):
        lon = self.cleaned_data['lon']
        if lon and not -180 < lon < 180:
            raise ValidationError('Invalid longitude value')
        return lon

    def clean_area(self):
        area = self.cleaned_data.get('area')
        neighborhood = self.cleaned_data.get('neighborhood')
        if area and neighborhood and area.neighborhood != neighborhood:
            raise ValidationError('If area is present it must be in same neighborhood as neighborhood')
        return area

class NeighborhoodLocationForm(LocationForm):
    def __init__(self, *args, **kwargs):
        super(NeighborhoodLocationForm, self).__init__(*args, **kwargs)
        self.fields.pop('neighborhood')

distribution/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from .models import Neighborhood, Area, Location
from accounts.models import User
from .forms import *

# Create your views here.

class NeighborhoodIndex(generic.ListView):
    template_name = 'distribution/neighborhood_index.html'
    context_object_name = 'neighborhoods'

    def get_queryset(self):
        return Neighborhood.objects.all()

def distribution_json(request):
    json_data = {}
    neighborhoods = Neighborhood.objects.all().order_by('pk')
    for n in neighborhoods:
        n_dict = {"name": n.name, "id": n.pk}
        if n.area.all():
            #n_dict['areas'] = [{'name': a.name, 'id': a.pk} for a in n.area.all().order_by('pk')]
            n_dict['areas'] = {a.pk: {'name': a.name, 'id': a.pk} for a in n.area.all().order_by('pk')}
            #no fuckin way, you can use list compression on a dict. huh, life is good
        json_data[n.pk] = n_dict
    return JsonResponse(json_data)

class NeighborhoodDetail(generic.DetailView):
    template_name = 'distribution/neighborhood_detail.html'
    model = Neighborhood
    context_object_name = 'neighborhood'

    def get_context_data(self,*args, **kwargs):
        context = super(NeighborhoodDetail, self).get_context_data(*args,**kwargs)
        context['users'] = User.objects.all()
        context['misc_locations'] = self.object.location.filter(area=None)
        context['hasAddresses'] = Location.objects.exclude(lon__isnull=True).exclude(lat__isnull=True)
        return context

def update_assigned_members(request, neighborhood):
    neighborhood = get_object_or_404(Neighborhood, slug=neighborhood)
    try:
        user = request.POST['member']
        action = request.POST['action']
    except:
        # Redisplay the view.
        return render(request, 'distribution/neighborhood_detail.html')
    else:
        user = User.objects.get(id=user)
        try:
            if action == "add":
                neighborhood.users.add(user)
                messages.success(request, f'successfully added {user} to route')
            elif action == "remove":
                 neighborhood.users.remove(user)
                 messages.success(request, f'successfully removed {user} from route')
        except:
            pass
    return HttpResponseRedirect(reverse('distribution:neighborhood_detail', args=(neighborhood.slug,)))

def area_create(request, neighborhood):
    neighborhood = get_object_or_404(Neighborhood, slug=neighborhood)
    try:
        name = request.POST['name']
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the view.
        return render(request, 'distribution/neighborhood_detail.html')
    else:
        area = Area(name=name, neighborhood=neighborhood)
        area.save()
        messages.success(request, 'successfully created area')
        return HttpResponseRedirect(reverse('distribution:neighborhood_detail', args=(neighborhood.slug,)))

def area_update(request, area):
    area = get_object_or_404(Area, pk=area)
    try:
        new_name = request.POST['new_name']
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the view.
        return render(request, 'distribution/detail.html')
    else:
        area.name = new_name
        area.save()
        messages.success(request, 'successfully updated name of area')
        return HttpResponseRedirect(reverse('distribution:neighborhood_detail', args=(area.neighborhood.slug,)))

class AreaDelete(SuccessMessageMixin, generic.edit.DeleteView):
    model = Area
    template_name = 'distribution/area_delete.html'
    success_message = 'successfully deleted area'

    def get_success_url(self):
        return reverse('distribution:neighborhood_detail', args=(self.object.neighborhood.slug,))

class LocationDetail(generic.DetailView):
    template_name = 'distribution/location_detail.html'
    model = Location
    context_object_name = 'location'

def location_create(request, neighborhood=None):
    if neighborhood:
        neighborhood = get_object_or_404(Neighborhood, slug=neighborhood)
        form = NeighborhoodLocationForm(request.POST or None)
        form.fields['area'].queryset = Area.objects.filter(neighborhood=neighborhood)
        #^filter to areas only in this neighborhood
        form.initial = {'area': request.GET.get('area')}
    else:
        form = LocationForm(request.POST or None)
        user_neighborhoods = request.user.neighborhoods
        form.neighborhood.queryset = sorted(Neighborhood.objects.all, key = lambda x: x in user_neighborhoods)
        #^sort where if a neighborhood is a user's, it should be first

    if form.is_valid(): #success, set user and save
        location = form.save(commit=False)
        if neighborhood:
            location.neighborhood = neighborhood
        location.created_by = request.user
        location.save()
        messages.success(request, "successfully added location %s" %(location.name))
        return HttpResponseRedirect(reverse('distribution:location_detail', kwargs={'neighborhood': location.neighborhood.slug, 'pk': location.id}))
    elif request.POST:
        messages.error(request, "please correct the errors listed")

    context = {'form': form, 'neighborhood': neighborhood, 'create': True}
    return render(request, 'distribution/location_form.html', context)

class LocationUpdate(SuccessMessageMixin, generic.edit.UpdateView):
    model = Location
    template_name = 'distribution/location_form.html'
    success_message = 'successfully updated location'
    form_class = LocationForm

    def get_context_data(self,*args, **kwargs):
        context = super(LocationUpdate, self).get_context_data(*args,**kwargs)
        context['neighborhood'] = self.object.neighborhood #supply this context for form
        context['update'] = True
        return context

    def get_success_url(self):
        return reverse_lazy('distribution:location_detail', kwargs={'neighborhood': self.object.neighborhood.slug, 'pk': self.object.id})

class LocationDelete(SuccessMessageMixin, generic.edit.DeleteView):
    model = Location
    template_name = 'distribution/location_delete.html'
    success_message = 'successfully deleted location'

    def get_success_url(self):
        return reverse('distribution:neighborhood_detail', kwargs={'slug': self.object.neighborhood.slug})

distribution/templates/distribution/area_delete.html
{% extends "base.html" %}

{% block title %}Delete area "{{ object }}"{% endblock %}

{% block content %}
<a href="{% url 'distribution:neighborhood_detail' object.neighborhood.slug %}">back to {{ object.neighborhood  }}</a>
<h1>delete area "{{ object }}"?</h1>

<p>Are you sure you want to delete this area?</p>
{% if object.child.all %}
<p><b>Doing so will remove this area (not change the neighborhood though) from all these locations:</b></p>
<ul>
	{% for child in page.child.all %}
	<li>{{ child }}</li>
	{% endfor %}
</ul>
{% endif %}

<form method="post">
	{% csrf_token %}
	{{ form }}
	<input type="submit" value="Delete">
</form>

{% endblock %}

distribution/templates/distribution/location_delete.html
{% extends "base.html" %}

{% block title %}Delete location "{{ object }}"{% endblock %}

{% block content %}
<a href="{% url 'distribution:location_detail' object.neighborhood.slug object.pk %}">back to {{ object  }}</a>
<h1>delete location "{{ object }}"?</h1>

<p>Are you sure you want to delete the location "{{ object }}"?</p>

<form method="post">
	{% csrf_token %}
	{{ form }}
	<input type="submit" value="Delete">
</form>

{% endblock %}

distribution/templates/distribution/location_detail.html
{% extends "base.html" %}

{% block title %}Distribution List | {{ location.neighborhood }} | {{ location }}{% endblock %}

{% block content %}
{% if location.neighborhood %}<a href="{% url 'distribution:neighborhood_detail' location.neighborhood.slug %}">back to {{ location.neighborhood }}</a>{% endif %}
<h1>{{ location }}</h1>
<p><a href='{% url 'distribution:location_update' location.neighborhood.slug location.pk %}'>edit</a> | <a href='{% url 'distribution:location_delete' location.neighborhood.slug location.pk %}'>delete</a></p>

{% if location.lon and location.lat %}
<div id='map'>
    Loading map...
</div>
{% endif %}

<div class='location'>
<p><b>Posters:</b> {{ location.get_has_poster_spot_display }}</p>
<p><b>Handbills:</b> {{ location.get_has_handbill_spot_display }}</p>
{% if location.address %}<b>Address:</b><p>{{ location.address }}</p>{% endif %}
{% if location.notes %}<b>Notes:</b><p class='pre'>{{ location.notes }}</p>{% endif %}
{% if location.hours %}<b>Hours:</b><p>{{ location.hours }}</p>{% endif %}
</div>

{% include 'distribution/location_map.html' with object=location %}

{% endblock %}

distribution/templates/distribution/location_form.html
{% extends "base.html" %}

{% block title %}{% if location %}Update Location | {{ location }}{% else %}Create a Location{% endif %}{% endblock %}

{% block content %}
{% if location %}<a href="{% url 'distribution:location_detail' location.neighborhood.slug location.pk %}">back to {{ location }}</a>
{% else %}
	{% if neighborhood %}
	<a href="{% url 'distribution:neighborhood_detail' neighborhood.slug %}">Back to {{ neighborhood }}</a>
	{% else %}<a href="{% url 'distribution:neighborhood_index' %}">Back to neighborhoods</a>
	{% endif %}
{% endif %}
<h1>{% if location %}Update Location | {{ location }}{% else %}Create a Location{% endif %}</h1>

<h2>Location Map</h2>
<div id='mapContainer'>
  <p>Drag the marker to change the location's position on the map.</p>
  <div id='map' style='margin-bottom:2em'>
      Loading map...
  </div>
</div>
<div>
  <input type="button" onclick="getLocationButtonPress()" value="I am at this location">
  <input id='clearBtn' type="button" onclick="clearLocation()" value="clear map position">
  {% if object.lat and object.lon %}<input id='resetBtn' type="button" onclick="resetLocation()" value="reset map position" title='reset map position to original value'>{% endif %}
</div>

<h2>Location Info</h2>
<form method="post">
  {% csrf_token %}
  <div class='form grid'>
    {{ form }}
    </div>
  <b id='getLocationError' class='hidden'></b>
  <input type="submit" value="Submit">
</form>

<script>
	{% if neighborhood %}
	//Neighborhood and areas dropdown stuff
	//so we don't want to show *all* the areas under *all* the neighborhoods at once to the user
	//we only show the areas under the currently selected neighborhood
	//so we add an event listener to the neighborhood input, and run some function where
	//we change the areas to be only the ones under that neighborhood (promise / json shit)
	var neighborhood_el = document.getElementById('id_neighborhood');
	var area_el = document.getElementById('id_area');
	var current_area = area_el.value;
	neighborhood_el.addEventListener("change", updateAreaChoices);

	function updateAreaChoices(){
		var neighborhood = neighborhood_el.value;
		if(area_el.value != "")
			current_area = area_el.value; //update the current area (what we *want* to select) if it's not emtpy
		fetch('{% url "distribution:distribution_json" %}')
   .then(response => {
		 if (!response.ok) {
			 throw new Error("HTTP error " + response.status);
		 }
		 return response.json();
   })
   .then(json => {
		 this.data = json;
     var areas = this.data[neighborhood]['areas']; //get the area json data
		 updateAreaChoicesHelper(areas, current_area);
   })
   .catch(function () {
		 this.dataError = true;
   })
	}
	//runs when we get the area json data from the promise
	function updateAreaChoicesHelper(areas, current_area){
		while (area_el.options.length != 1) { //remove all options except first
			area_el.remove(1);
		}
		for(const [key, value] of Object.entries(areas)){ //loop through our dictionary
			area_el.add(new Option(value['name'], key, false, key == current_area)); //add options back
			//^key == current_area: select option if it's the current area
		}
	}
	updateAreaChoices(); //do it for the first time
	{% endif %}
</script>
{% include 'distribution/location_map.html' %}

{% endblock %}

distribution/templates/distribution/neighborhood_detail.html
{% extends "base.html" %}

{% block title %}Distribution List | {{ neighborhood }}{% endblock %}

{% block content %}
<a href="{% url 'distribution:neighborhood_index' %}">back to neighborhoods</a>
<h1>{{ neighborhood }}</h1>

<div>
  members assigned to this route: {% for u in neighborhood.users.all %}{{ u }}{% if forloop.counter != neighborhood.users.count %}, {% endif %}{% endfor %} |
  {% if neighborhood.users.count != users.count %}
  <form action="{% url 'distribution:update_assigned_members' neighborhood.slug %}" method="post" class="inline hidden" id='add_member_form' name='add_member_form'>
    {% csrf_token %}
    <select name="member" id="id_add_member" onblur="add_member()" onchange="document.forms['add_member_form'].submit()" required>
      <option value="">---------</option>
      {% for u in users %}
      {% if u not in neighborhood.users.all %}<option value="{{ u.pk }}">{{ u }}</option>{% endif %}
      {% endfor %}
    </select>
    <input type="hidden" value="add" name="action" id="id_action">|
  </form>
  <a href='#' onclick="add_member()">add member to this route</a> |
  {% endif %}
  {% if neighborhood.users.all %}
  <form action="{% url 'distribution:update_assigned_members' neighborhood.slug %}" method="post" class="inline hidden" id='remove_member_form' name='remove_member_form'>
    {% csrf_token %}
    <select name="member" id="id_remove_member" onblur="remove_member()" onchange="document.forms['remove_member_form'].submit()" required>
      <option value="">---------</option>
      {% for u in neighborhood.users.all %}
      <option value="{{ u.pk }}">{{ u }}</option>
      {% endfor %}
    </select>
    <input type="hidden" value="remove" name="action" id="id_action">|
  </form>
  <a href='#' onclick="remove_member()">remove member from route</a>
  {% endif %}
</div>

<h2>Locations</h2>
{% if hasAddresses.count > 0 %}
<div id='map'>
    Loading map...
</div>
{% endif %}
{% if neighborhood.location.count > 1 %}
<button onclick="toggle_details(this)">expand all</button>
{% endif %}
{% if neighborhood.location.all or neighborhood.area.all %}
{% for a in neighborhood.area.all %}
<div class='area_container'>
  <h3 id='area{{ forloop.counter0 }}'>{{ a }}</h3>
  <form action="{% url 'distribution:area_update' a.pk %}" method="post" class="inline hidden" id='form{{ forloop.counter0 }}' name='area_update_{{ forloop.counter0 }}'>
    {% csrf_token %}
    <input type="text" name="new_name" id="new_name{{ forloop.counter0 }}" value="{{ a }}" onblur="rename_area({{ forloop.counter0 }})" onchange="document.forms['area_update_{{ forloop.counter0 }}'].submit()" required>
  </form> |
  <a href='#' onclick="rename_area({{ forloop.counter0 }})">rename</a> |
  <a href='{% url 'distribution:area_delete' a.pk %}'>delete</a>
</div>

{% for l in a.location.all %}
<details class='location'>
  <summary>{{ l }} | <a href="{% url 'distribution:location_detail' neighborhood.slug l.id %}">detail page</a></summary>
  <p>Posters: <span>{{ l.get_has_poster_spot_display }}</span></p>
  <p>Handbills: <span>{{ l.get_has_handbill_spot_display }}</span></p>
  {% if l.address %}<p>Address: <span>{{ l.address }}</span></p>{% endif %}
  {% if l.notes %}<p>Notes: <span>{{ l.notes }}</span></p>{% endif %}
  {% if l.hours %}<p>Hours: <span>{{ l.hours }}</span></p>{% endif %}
</details>
{% endfor %}
<p><a href='{% url 'distribution:location_create' neighborhood.slug %}?area={{ a.id }}'>add a location under this area</a></p>
{% endfor %}

<h3>Misc. Locations</h3>
{% for l in misc_locations %}
<details class='location'>
  <summary>{{ l }} | <a href="{% url 'distribution:location_detail' neighborhood.slug l.id %}">detail page</a></summary>
  <p>Posters: <span>{{ l.get_has_poster_spot_display }}</span></p>
  <p>Handbills: <span>{{ l.get_has_handbill_spot_display }}</span></p>
  {% if l.address %}<p>Address: <span>{{ l.address }}</span></p>{% endif %}
  {% if l.notes %}<p>Notes: <span class='pre'>{{ l.notes }}</span></p>{% endif %}
  {% if l.hours %}<p>Hours: <span>{{ l.hours }}</span></p>{% endif %}
</details>
{% endfor %}

<p><a href="{% url 'distribution:location_create' neighborhood.slug %}">add a location</a></p>
{% else %}<p>There aren't any locations under this neighborhood. <a href="{% url 'distribution:location_create' neighborhood.slug %}">Add a location</a></p>
{% endif %}

<details>
  <summary>add sub-area/street to this neighborhood</summary>
  <form action="{% url 'distribution:area_create' neighborhood.slug %}" method="post" name="area_create">
    {% csrf_token %}
    <label for="name">area name:</label>
    <input type="text" name="name" id="name" value="" required>
    <input type="submit" value="Add area">
  </form>
</details>

<script>
  function rename_area(area_id){
    if(0 < area_id < {{ neighborhood.area.count }}){
      var text = document.getElementById('area' + area_id);
      var form = document.getElementById('form' + area_id);
      var input = document.getElementById('new_name' + area_id);
      form.classList.toggle('hidden');
      text.classList.toggle('hidden');
      input.focus(); //focus input
      input.selectionStart = input.selectionEnd = input.value.length; //move cursor to end
    }
  }

  function add_member(){
    var form = document.getElementById('add_member_form');
    var input = document.getElementById('id_add_member');
    form.classList.toggle('hidden');
    input.focus();
  }
  function remove_member(){
    var form = document.getElementById('remove_member_form');
    var input = document.getElementById('id_remove_member');
    form.classList.toggle('hidden');
    input.focus();
  }

  var expand = true;
  function toggle_details(button) {
    var els = document.getElementsByTagName('details')
    for (var i = 0; i < els.length; i++) {
      if (els[i].classList.contains('location')){ //target only location class details
	els[i].open = expand;
      }
    }
    if(expand)
      button.innerText = 'collapse all';
    else
      button.innerText = 'expand all';
    expand = !expand;
  }
</script>
{% if hasAddresses.count > 0 %}
{% include 'distribution/neighborhood_map.html' with objects=hasAddresses %}
{% endif %}
{% endblock %}

distribution/templates/distribution/neighborhood_index.html
{% extends "base.html" %}

{% block title %}Pin Up Posters Courrier Collective Distribution List{% endblock %}

{% block content %}
<h1>Neighborhoods</h1>
<ul class='neighborhoods'>
	{% for neighborhood in neighborhoods %}
	<li><a href="{% url 'distribution:neighborhood_detail' neighborhood.slug %}">{{ neighborhood }}</a>: {{ neighborhood.location.count }} location{{ neighborhood.location.count|pluralize }}, {{ neighborhood.posterspots }} poster spot{{ neighborhood.posterspots|pluralize }}, {{ neighborhood.handbillspots }} handbill spot{{ neighborhood.handbillspots|pluralize }}</li>
	{% endfor %}
</ul>
{% endblock %}

distribution/templates/distribution/neighborhood_map.html
<script src='https://api.mapbox.com/mapbox-gl-js/v2.9.1/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v2.9.1/mapbox-gl.css' rel='stylesheet' />

<script>
	/*var addressField = document.getElementById('id_address');
	var addressWrapper = document.getElementById('addressWrapper');

	function addressExists(){
		if (addressField.value == "") {
			document.getElementById('map').style.display = 'none';
    		document.getElementById('coordinates').style.display = 'none';
    		document.getElementById('id_lon').value = null; document.getElementById('id_lat').value = null;
    		return false;
		} else {
			document.getElementById('map').style.display = 'inherit';
    		document.getElementById('coordinates').style.display = 'inherit';
    		return true;
		}
	}*/

	mapboxgl.accessToken = 'pk.eyJ1IjoiY2RpYW1vbmQyNSIsImEiOiJjbDdkaHJqcnowNG1kM3dtZm9najd0Z3NsIn0.bywNebFGqlnBzNEjAI3ePg';

	var map = new mapboxgl.Map({
		container: 'map',
		style: 'mapbox://styles/mapbox/streets-v11',
		{% if object.lat and object.lon %}center: [{{ object.lon }}, {{ object.lat }}], zoom: 14
		{% else %}center: [-79.9528409, 40.455588], zoom: 12
		{% endif %}
	});

	var el;
  var popup;
  var marker;
  {% for object in objects %}
  el = document.createElement('div');
	el.className = 'marker';

  popup = new mapboxgl.Popup({ offset: 45, className: 'location' }).setHTML(
    //"<p><a href='{% url 'distribution:location_detail' object.neighborhood.slug object.id %}' target='_blank'>{{ object|escapejs }}</a>"
    `<p><a href='{% url 'distribution:location_detail' object.neighborhood.slug object.id %}' target='_blank'>{{ object|escapejs }}</a></p>
<p><b>Posters:</b> {{ object.get_has_poster_spot_display }}</p>
<p><b>Handbills:</b> {{ object.get_has_handbill_spot_display }}</p>
{% if object.address %}<b>Address:</b><p>{{ object.address }}</p>{% endif %}
{% if object.notes %}<b>Notes:</b><p class='pre'>{{ object.notes }}</p>{% endif %}
{% if object.hours %}<b>Hours:</b><p>{{ object.hours }}</p>{% endif %}
`
  );

	marker = new mapboxgl.Marker({
		element: el,
		anchor: 'bottom'
	})
	.setLngLat([{{ object.lon }}, {{ object.lat }}])
  .setPopup(popup)
	.addTo(map);
  {% endfor %}
	</script>