clockout/urls.py
from django.urls import path

from . import views

app_name = 'clockout'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('new', views.new, name='new'),
]

pinup/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse
from django.views.generic.base import RedirectView

def robots(request):
    return HttpResponse('User-agent: *\nDisallow: /', content_type='text/plain')

urlpatterns = [
    path('robots.txt', robots),
    path('admin/', admin.site.urls),
    path('wiki/', include('wiki.urls')),
    path('distribution/', include('distribution.urls')),
    path('clockout/', include('clockout.urls')),
    path('calendar/', include('poster_calendar.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', RedirectView.as_view(pattern_name='wiki:index', permanent=True), name='index')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wiki/urls.py
from django.urls import path, register_converter

from . import views, converters
register_converter(converters.PathConverter, 'page')

app_name = 'wiki'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
	path('_create', views.create, name='create'),
	path('_upload', views.upload, name='upload'),
	path('<page:page_path>', views.detail, name='detail'),
	path('<page:page_path>/_create', views.create, name='create'),
	path('<page:page_path>/_upload', views.upload, name='upload'),
	path('<page:page_path>/_update', views.update, name='update'),
	path('<page:page_path>/_delete', views.delete, name='delete'),
	path('<page:page_path>/_revert/<int:edit_number>', views.revert, name='revert'),
	path('<page:page_path>/_history', views.history, name='history'),

	#path('<page:page_path>/_move', views.page_move, name='page_move'),
	#path('<page:page_path>/_clone', views.page_clone, name='page_clone'),
	#path('<page:page_path>/_source', views.page_source, name='page_source'),
]

clockout/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator

from accounts.models import User
from distribution.models import Neighborhood

BOOL_CHOICES = ((True, 'Yes'), (False, 'No'))
class ClockOutResponse(models.Model):
    user = models.ForeignKey(User, verbose_name="Name", on_delete=models.SET_NULL, null=True)
    week_number = models.PositiveSmallIntegerField("Week Number", default = 1, validators=[MinValueValidator(1), MaxValueValidator(52)])
    neighborhoods = models.ManyToManyField(Neighborhood, verbose_name="Neighborhoods on route")
    #^autofill this with user's default neighborhoods
    completed_route = models.BooleanField("Completed route?", choices=BOOL_CHOICES)
    need_someone = models.BooleanField("Do you need someone to complete this route for you?", choices=BOOL_CHOICES)
    notes = models.TextField("Notes about route/this week", blank=True, null=True)
    submitted = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-week_number', '-submitted']

    def __str__(self):
        return f'{self.user} clocked out on {self.submitted}'

clockout/forms.py
from django import forms
from .models import ClockOutResponse

class ClockOutForm(forms.ModelForm):
    class Meta:
        model = ClockOutResponse
        exclude = ['user', 'submitted']
        widgets = {
            'neighborhoods': forms.CheckboxSelectMultiple(),
            'notes': forms.Textarea(attrs={'rows':0, 'cols':0}),
	    }

clockout/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.contrib import messages

from .models import ClockOutResponse
from .forms import *
from django.utils import timezone

class IndexView(generic.ListView):
    template_name = 'clockout/index.html'
    context_object_name = 'responses'

    def get_queryset(self):
        #return ClockOutResponse.objects.all()
        responses = ClockOutResponse.objects.all()
        responses_dict = {}
        for r in responses:
            responses_dict[r.week_number] = responses_dict.get(r.week_number, []) + [r]
        return responses_dict

def new(request):
    form = ClockOutForm(initial={
        'neighborhoods': [n.id for n in request.user.neighborhoods.all()],
        'week_number': timezone.now().isocalendar()[1],
        })
    #print(form.initial)
    if request.method == "POST":
        form = ClockOutForm(request.POST, initial={
            'neighborhoods': [n.id for n in request.user.neighborhoods.all()],
            'week_number': timezone.now().isocalendar()[1]
            })
        if form.is_valid():
            response = form.save(commit=False)
            response.user = request.user
            response.save()
            form.save_m2m() #save many-to-many with commit=False

            messages.success(request, "Submitted clockout form")
            return HttpResponseRedirect(reverse('clockout:index'))
    context = {'form': form}
    return render(request, 'clockout/form.html', context)

clockout/templates/clockout/form.html
{% extends "base.html" %}

{% block title %}Clock Out Form{% endblock %}

{% block content %}
<a href='{% url "clockout:index" %}'>back to clockout responses</a>
<h1>New Clockout</h1>
<form method="post">
  {% csrf_token %}
  <div class='form stacked'>
  {{ form }}
  </div>
  <input type="submit" value="Submit">
</form>

<script>
  var completed_el = document.getElementById("id_completed_route")
  var need_someone_el = document.getElementById("id_need_someone")
  completed_el.addEventListener("change", completedAutofill);
  completedAutofill();

  function completedAutofill() {
    if (completed_el.value == "True")
      need_someone_el.value = "False";
  }
</script>
{% endblock %}

clockout/templates/clockout/index.html
{% extends "base.html" %}

{% block title %}Clock Out Responses{% endblock %}

{% block content %}
<h1>Clock Out Responses</h1>
<p><a href="{% url 'clockout:new' %}">submit new clock out</a></p>
{% if responses %}
{% for week, week_items in responses.items %}
<!--<h2>Week {{ week }}</h2>
<ul>
  {% for response in week_items %}
  <li>{{ response }}</li>
  {% endfor %}
</ul>-->
<div class='calendar_entry'>
  <h2>week {{ week }}</h2>
  <div class='entry_container'>
  {% for response in week_items %}
  <div class='entry'>
    {% if response.completed_route %}<div class='tag is-success'>completed</div>{% else %}<div class='tag is-error'>not completed</div>{% endif %}
    {% if response.need_someone %}<div class='tag is-error'>needs help</div>{% endif %}
    <h3>{{ response.user }}</h3>
    <p class='info'>clocked out {{ response.submitted }}</p>
    <p class='info'>neighborhoods: {% for n in response.neighborhoods.all %}{{ n }}{% if forloop.counter != response.neighborhoods.count %}, {% endif %}{% endfor %}</p>
    {% if not response.completed_route or response.need_someone %}<p>{% if not response.completed_route %}Uncompleted{% endif %} route. {% if response.need_someone %}Needs someone to complete this route.{% endif %}</p>{% endif %}
    <p>{% if response.notes %}{{ response.notes }}{% else %}No notes{% endif %}</p>
  </div>
  {% endfor %}
  </div>
</div>
{% endfor %}
{% else %}
<p>No responses found</p>
{% endif %}
{% endblock %}